USE inventaris_lab_db;

INSERT INTO inventaris (nama_barang, kategori, kondisi, jumlah) VALUES
('Meja Distinctio', 'Komputer', 'Baik', 49),
('Kursi Modi', 'Alat Tulis', 'Perlu Perbaikan', 1),
('Mouse Culpa', 'Komputer', 'Rusak', 21),
('Switch Corporis', 'Elektronik', 'Perlu Perbaikan', 18),
('Switch Nisi', 'Elektronik', 'Baik', 22),
('Router Sed', 'Komputer', 'Baik', 19),
('Kursi Recusandae', 'Laboratorium', 'Rusak', 20),
('Printer Perspiciatis', 'Komputer', 'Rusak', 41),
('Keyboard Saepe', 'Alat Tulis', 'Perlu Perbaikan', 1),
('Switch Nemo', 'Perabot', 'Baik', 25),
('Keyboard Aperiam', 'Elektronik', 'Baik', 17),
('Monitor Velit', 'Komputer', 'Rusak', 49),
('Komputer Dolore', 'Elektronik', 'Perlu Perbaikan', 38),
('Router Aliquid', 'Jaringan', 'Perlu Perbaikan', 3),
('Printer Dolorum', 'Elektronik', 'Rusak', 5),
('Mouse Enim', 'Jaringan', 'Rusak', 35),
('Switch Minima', 'Laboratorium', 'Rusak', 17),
('Router Similique', 'Jaringan', 'Baik', 34),
('Router Et', 'Komputer', 'Baik', 5),
('Komputer Alias', 'Perabot', 'Baik', 13),
('Switch Consectetur', 'Alat Tulis', 'Rusak', 27),
('Proyektor Maiores', 'Alat Tulis', 'Perlu Perbaikan', 28),
('Monitor In', 'Elektronik', 'Baik', 37),
('Mouse Similique', 'Komputer', 'Perlu Perbaikan', 42),
('Komputer Quod', 'Elektronik', 'Perlu Perbaikan', 18),
('Switch Quos', 'Alat Tulis', 'Perlu Perbaikan', 34),
('Proyektor Vitae', 'Laboratorium', 'Perlu Perbaikan', 6),
('Komputer Aut', 'Komputer', 'Perlu Perbaikan', 17),
('Printer Accusamus', 'Laboratorium', 'Perlu Perbaikan', 4),
('Switch Eligendi', 'Alat Tulis', 'Rusak', 16),
('Router Voluptates', 'Perabot', 'Baik', 6),
('Komputer Voluptatem', 'Komputer', 'Perlu Perbaikan', 13),
('Switch Nisi', 'Laboratorium', 'Perlu Perbaikan', 48),
('Monitor Sapiente', 'Jaringan', 'Baik', 30),
('Meja Sint', 'Alat Tulis', 'Perlu Perbaikan', 39),
('Proyektor Ipsum', 'Laboratorium', 'Perlu Perbaikan', 29),
('Printer Nostrum', 'Elektronik', 'Perlu Perbaikan', 38),
('Proyektor Nihil', 'Jaringan', 'Baik', 24),
('Meja Voluptate', 'Perabot', 'Perlu Perbaikan', 13),
('Meja Magni', 'Komputer', 'Baik', 45),
('Keyboard Repellat', 'Alat Tulis', 'Baik', 7),
('Switch Repellat', 'Elektronik', 'Perlu Perbaikan', 50),
('Keyboard Nemo', 'Alat Tulis', 'Baik', 27),
('Router Neque', 'Laboratorium', 'Rusak', 48),
('Komputer Tempore', 'Jaringan', 'Rusak', 24),
('Kursi Quas', 'Jaringan', 'Perlu Perbaikan', 44),
('Monitor Rerum', 'Laboratorium', 'Baik', 50),
('Proyektor Minus', 'Jaringan', 'Baik', 2),
('Proyektor Ut', 'Elektronik', 'Perlu Perbaikan', 32),
('Monitor Doloremque', 'Perabot', 'Perlu Perbaikan', 16),
('Kursi Libero', 'Jaringan', 'Rusak', 11),
('Meja Soluta', 'Alat Tulis', 'Rusak', 45),
('Proyektor Perferendis', 'Elektronik', 'Rusak', 16),
('Monitor Natus', 'Elektronik', 'Rusak', 2),
('Proyektor Unde', 'Laboratorium', 'Baik', 19),
('Proyektor Quas', 'Jaringan', 'Rusak', 15),
('Monitor Autem', 'Perabot', 'Baik', 19),
('Mouse Minima', 'Laboratorium', 'Baik', 4),
('Mouse Architecto', 'Jaringan', 'Baik', 20),
('Proyektor Debitis', 'Perabot', 'Perlu Perbaikan', 40),
('Meja Velit', 'Jaringan', 'Baik', 43),
('Mouse Molestiae', 'Jaringan', 'Rusak', 12),
('Proyektor Sint', 'Jaringan', 'Baik', 8),
('Monitor Possimus', 'Komputer', 'Perlu Perbaikan', 22),
('Komputer Ratione', 'Komputer', 'Baik', 29),
('Kursi Animi', 'Perabot', 'Rusak', 1),
('Kursi Eaque', 'Elektronik', 'Perlu Perbaikan', 18),
('Printer Assumenda', 'Komputer', 'Perlu Perbaikan', 22),
('Switch Saepe', 'Alat Tulis', 'Rusak', 13),
('Komputer Sapiente', 'Alat Tulis', 'Rusak', 27),
('Komputer Voluptates', 'Komputer', 'Perlu Perbaikan', 10),
('Kursi Ab', 'Laboratorium', 'Baik', 20),
('Keyboard Inventore', 'Elektronik', 'Perlu Perbaikan', 4),
('Meja Iste', 'Komputer', 'Baik', 29),
('Switch Qui', 'Perabot', 'Baik', 16),
('Meja Sed', 'Alat Tulis', 'Rusak', 29),
('Router At', 'Perabot', 'Perlu Perbaikan', 46),
('Switch Sit', 'Komputer', 'Perlu Perbaikan', 13),
('Meja Reiciendis', 'Alat Tulis', 'Rusak', 50),
('Kursi Dolore', 'Jaringan', 'Rusak', 3),
('Proyektor Inventore', 'Laboratorium', 'Baik', 2),
('Printer Voluptas', 'Perabot', 'Perlu Perbaikan', 18),
('Switch Officiis', 'Komputer', 'Rusak', 45),
('Kursi Reiciendis', 'Alat Tulis', 'Baik', 3),
('Mouse Dolore', 'Alat Tulis', 'Baik', 21),
('Keyboard Voluptates', 'Alat Tulis', 'Baik', 12),
('Mouse Corporis', 'Laboratorium', 'Baik', 14),
('Proyektor Rerum', 'Perabot', 'Baik', 28),
('Mouse Laborum', 'Komputer', 'Perlu Perbaikan', 3),
('Keyboard Adipisci', 'Komputer', 'Perlu Perbaikan', 33),
('Proyektor Nesciunt', 'Jaringan', 'Rusak', 12),
('Monitor Ea', 'Alat Tulis', 'Rusak', 47),
('Komputer Iste', 'Jaringan', 'Rusak', 41),
('Komputer Ducimus', 'Laboratorium', 'Baik', 7),
('Monitor Quisquam', 'Alat Tulis', 'Rusak', 14),
('Router Suscipit', 'Laboratorium', 'Perlu Perbaikan', 21),
('Meja Non', 'Jaringan', 'Perlu Perbaikan', 49),
('Keyboard Harum', 'Perabot', 'Perlu Perbaikan', 50),
('Komputer Ea', 'Alat Tulis', 'Rusak', 0),
('Kursi In', 'Komputer', 'Perlu Perbaikan', 39);
